-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg/W5RsxnKWiicOk+c
67vVDvpnYXLK7bIrCAHgnkf45NOgCgYIKoZIzj0DAQehRANCAARuyixkvvxHXXW6
JriPBluLzKwb12WEfi+8wsYA2SzoQS1QHOksY4sg+vaKihGrtgcMhbQZYRjFOaTB
Ry2Oksfx
-----END PRIVATE KEY-----